### ISSUE TITLE
Alphabetical order of motors in scan header - question

### ISSUE THREAD

**Issue by cpt-majkel** [vasole/pymca#1029]
Hi, 

we have migrated from PyMca 5.5.5 to 5.8.2 and discovered that now motors in scan header are ordered alphabetically and not by the order as in the source file (as it was previously, we are using `.dat`). Is it a desired feature? Is it possible to switch it back to source order? It would be better for us since we are ordering motors in hearder by importance.

Cheers,
Michal

**Comment by vasole** [comment]
Yes, it is a desired feature because if one is interested on a particular motor it is easier to find it.

I will take a look to see if I can offer the best of both worlds.

**Comment by vasole** [comment]
It should be solved by #1032 and available in next release.

I have enabled to copy the table to the clipboard too.

**Comment by cpt-majkel** [comment]
Thanks for a quick MR!
