### ISSUE TITLE
[5.9.2] Replace assert_array_equal by assert_allclose in tests to avoid  floating point comparison failures

### ISSUE THREAD

**Issue by picca** [vasole/pymca#1066]
Hello armando.

In order to pass tests I need this patch in PyMCA.

https://sources.debian.org/src/pymca/5.8.7+dfsg-2/debian/patches/0002-Replace-assert_array_equal-by-assert_allclose-in-tes.patch/

Could you integrate it into the PyMCA sources ?

thanks

Frédéric

**Comment by picca** [comment]
I did not try without the patch, I should remove it and see what is going on...

thanks

Fred

**Comment by picca** [comment]
it works on i386 :)

Thanks

Fred

https://ci.debian.net/packages/p/pymca/testing/i386/43651255/

**Comment by vasole** [comment]
I guess it works on 64-bit machines too. Is it the case? If so, we can close this issue.
