### ISSUE TITLE
Bliss HDF5 files: all strings are marked as "BrokenLink"

### ISSUE THREAD

**Issue by woutdenolf** [vasole/pymca#1091]
Any Bliss file has this issue:

![image](https://github.com/user-attachments/assets/33ad9bc1-4ced-4bb5-b629-3f843750df0c)

**Comment by woutdenolf** [comment]
FYI silx does not have this issue

![image](https://github.com/user-attachments/assets/75075bb2-7ab4-41a5-9ea1-2d36905e2e10)

**Comment by vasole** [comment]
Strange, the title is read into the description.

Beamline, PyMca version, h5py version, bliss version?

**Comment by woutdenolf** [comment]
Pymca 5.9.3, Bliss 2.1, h5py 3.11.0

**Comment by woutdenolf** [comment]
This is what the blisswriter does: https://gitlab.esrf.fr/bliss/bliss/-/blob/master/blisswriter/src/blisswriter/io/nexus.py#L127
