### ISSUE TITLE
Slow file tree traversing on NFS automount.

### ISSUE THREAD

**Issue by kif** [vasole/pymca#1095]
Hi Armando,

An user reported some bugs on ESRF control computer when accessing files over the NFS automount: when browsing to the root of all NFS-mount, the file-dialog (from PyMca) mounts all possible network filesystem which takes several minutes on the `/data/visitor`. Do you know if there is a way to bypass the mounting of all those filesystems at the Qt level ? Or is this a necessary evil ?

Actually, the name of the share is all that would be needed, one should not need to mount them all to browse one of them !

Cheers, 
Jerome

**Comment by kif** [comment]
The issue is confirmed to be related to  NFS:
```
kieffer@scisoft10:~$ mount |wc
    137     822   25174
kieffer@scisoft10:~$ pymca
kieffer@scisoft10:~$ mount |wc
   1444    8664  377660
```
Accessing `/data/visitor` mounts 1300 folders.

There is no issue when using GPFS, I already suggested to switch to GPFS to the beamline staff.

Remains the question, can a work-around be implemented at the Python/Qt level ?

**Comment by vasole** [comment]
No, there is no workaround as far as I know if you use the Qt file dialog as it scans all the tree for thumbnails or similar. When you have network disks can be really painful (particularly if they are unmounted!)

The only thing is to forget about the comfort provided by the Qt file dialog and to use the operating system file dialog.

That is achieved by starting PyMca as:

`pymca --nativefiledialogs=True`  (setting equal to 1 should also do the job)

You can save the PyMca settings or edit the PyMca.ini  file and look for the keyword to set the variable for what is best for the user

http://www.silx.org/doc/PyMca/dev/customization/settings/index.html

**Comment by vasole** [comment]
As a side note, I have tested with PySide6 on scisoft10 and the problem does not seem to be there.

**Comment by kif** [comment]
Very valuable piece of info: I have several bugs related to (py-)Qt5 which are complicated to work-around (except bypassing qt5->qt6)

**Comment by vasole** [comment]
Can this be closed?
