### ISSUE TITLE
[silx] force silx > 0.6.0 when available in Debian

### ISSUE THREAD

**Issue by PiRK** [vasole/pymca#114]
Related to #109. 

Important bugfixes will be released in `0.6.1`.

Do it in Debian packaging scripts and setup.py

**Comment by PiRK** [comment]
We can force silx >=0.7.0, now. It is available in Debian and it fixes more issues (importantly, it improves the DataViewer API).

**Comment by vasole** [comment]
Yes, but that is to be made in the silx branch.
