### ISSUE TITLE
[silx] Use sift from silx

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#122]
No reason to maintain two implementations.

**Comment by kif** [comment]
On Wed, 08 Nov 2017 08:24:47 +0000 (UTC)
V. Armando Solé <notifications@github.com> wrote:

> No reason to maintain two implementations.


There is a refactoring pending for silx which will have large impacts on the API ...
you should wait

**Comment by PiRK** [comment]
This one can be closed.
