### ISSUE TITLE
[nxdataview] Error with latest silx master

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#144]
Reading the example with multiple curves:

![pymcasilxmaster](https://user-images.githubusercontent.com/5636251/35473328-26f13eec-037f-11e8-9a2d-9f7f162cf888.png)

**Comment by PiRK** [comment]
Ooops. I introduced a hasty API change when I implemented auxiliary signals. I will fix it in PyMca and also maintain the old API in silx (with a deprecation warning).
