### ISSUE TITLE
[Console] Quit on console quits the application.

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#169]
If the user types quit() on the console, the whole application quits.

**Comment by PiRK** [comment]
A possible explanation why the behavior is different in silx is that this line is missing from  `silx.gui.console`: https://github.com/vasole/pymca/blob/def751bc19a005ed4866c37060cfc3acfd9271d5/PyMca5/PyMcaGui/misc/QIPythonWidget.py#L119

But I'm currently unable to test, because of other issues.

**Comment by vasole** [comment]
Good finding! Let's see if we can make a proper cleanup of the console variables and a proper closing of the widget.
