### ISSUE TITLE
[silx 0.7.0] Opening twice a dataset and viewing it as image gives a ColormapDialog error

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#173]
@t20100 @PiRK @payno

The error is not present under silx 0.6.1

![image](https://user-images.githubusercontent.com/5636251/37258024-c678857e-2571-11e8-92d7-d93352e3d61d.png)

**Comment by t20100** [comment]
@vasole, how can we reproduce it?

**Comment by vasole** [comment]
It has to be reproduced at the PyMca side:

1 - Open the information associated to a dataset of dimension 2 or higher (right-click on dataset)
2 - Show the image view
3 - Close the window
4 - Repeat steps 1 and 2
