### ISSUE TITLE
[HDF5] Provide output in HDF5 format

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#180]
It has to follow the NXprocess approach of the fit all plugin. That means

- Fits and maps saved as NXdata making use of auxiliary_signals
- Configuration used saved to the HDF5 file
- The configuration from the HDF5 file must be readable back and used
- The saved maps must be readable back wherever PyMca can currently read a list of EDF files.

**Comment by PiRK** [comment]
Should we add a save button to all fit widgets ? Or only some specific fits ?

**Comment by vasole** [comment]
What I had in mind was mainly XRF related stuff. It is true that it can also be made for the ROI Imaging simple fit plugin.

**Comment by vasole** [comment]
Closed by #440
