### ISSUE TITLE
[debian] AttributeError: 'module' object has no attribute 'QGLWidget'

### ISSUE THREAD

**Issue by picca** [vasole/pymca#204]
Hello, whne building pymca, I get this error

WARNING: autodoc: failed to import module u'PyMca5.Object3D.SceneGLWidget'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc/importer.py", line 140, in import_module
    __import__(modname)
  File "/<<BUILDDIR>>/pymca-5.3.0+dfsg/.pybuild/cpython2_2.7_pymca5/build/PyMca5/Object3D/SceneGLWidget.py", line 36, in <module>
    from . import Object3DRedBookFont
  File "/<<BUILDDIR>>/pymca-5.3.0+dfsg/.pybuild/cpython2_2.7_pymca5/build/PyMca5/Object3D/Object3DRedBookFont.py", line 153, in <module>
    class TestWidget(qt.QGLWidget):
AttributeError: 'module' object has no attribute 'QGLWidget'

on Debian unstable the Qt5 available is 5.10.
It seems that the pyqt5 removed this old compatibility layer...

**Comment by vasole** [comment]
Strange. I am using Qt 5.10.1 under windows and the error is not there.

I will have to implement the workaround similar to the one in:

https://github.com/silx-kit/silx/blob/master/silx/gui/_glutils/OpenGLWidget.py

Two options, either you wait for the patch, either you totally remove the Object3D folder.

**Comment by vasole** [comment]
@PiRK 

Do you have the time to implement the workaround in PyMca?

**Comment by vasole** [comment]
It seems that replacing all occurrences of QGLWidget by QOpenGLWidget everything should work for your debian version but we need to implement the workaround for the case somebody insists on using PyMca with debian 8 or PyQt4.

**Comment by PiRK** [comment]
It seems minimalistic patch would be:
```
diff --git a/PyMca5/Object3D/Object3DRedBookFont.py b/PyMca5/Object3D/Object3DRedBookFont.py
index b4b5125..bd20729 100644
--- a/PyMca5/Object3D/Object3DRedBookFont.py
+++ b/PyMca5/Object3D/Object3DRedBookFont.py
@@ -30,6 +30,13 @@
 import numpy
 from . import Object3DQt as qt
 
+if hasattr(qt, 'QOpenGLWidget'):  # PyQt>=5.4
+    _BaseOpenGLWidget = qt.QOpenGLWidget
+elif hasattr(qt, 'QGLWidget'):
+    _BaseOpenGLWidget = qt.QGLWidget
+else:
+    raise ImportError("QOpenGLWidget is not available.")
+
 rasters = numpy.array([
  [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
  [0x00, 0x00, 0x18, 0x18, 0x00, 0x00, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18],
@@ -150,9 +157,9 @@ def printString(self, text):
         GL.glPopAttrib()
 
 
-class TestWidget(qt.QGLWidget):
+class TestWidget(_BaseOpenGLWidget):
     def initializeGL(self):
-        qt.QGLWidget.initializeGL(self)
+        _BaseOpenGLWidget.initializeGL(self)
         self.redBookFont = Object3DRedBookFont()
         self.redBookFont.initialize()
 
diff --git a/PyMca5/Object3D/SceneGLWidget.py b/PyMca5/Object3D/SceneGLWidget.py
index 6eb8d4c..6872401 100644
--- a/PyMca5/Object3D/SceneGLWidget.py
+++ b/PyMca5/Object3D/SceneGLWidget.py
@@ -43,7 +43,16 @@
 DEBUG = 0
 SCENE_MATRIX = True
 
-class SceneGLWidget(qt.QGLWidget):
+
+if hasattr(qt, 'QOpenGLWidget'):  # PyQt>=5.4
+    _BaseOpenGLWidget = qt.QOpenGLWidget
+elif hasattr(qt, 'QGLWidget'):
+    _BaseOpenGLWidget = qt.QGLWidget
+else:
+    raise ImportError("QOpenGLWidget not available.")
+
+
+class SceneGLWidget(_BaseOpenGLWidget):
 
     sigScaleChanged = qt.pyqtSignal(object)
     sigObjectSelected = qt.pyqtSignal(object)
@@ -51,8 +60,8 @@ class SceneGLWidget(qt.QGLWidget):
     sigMouseMoved = qt.pyqtSignal(object)
 
     def __init__(self, parent = None, scene=None):
-        #qt.QGLWidget.__init__(self, qt.QGLFormat(qt.QGL.SampleBuffers), parent)
-        qt.QGLWidget.__init__(self, parent)
+        #_BaseOpenGLWidget.__init__(self, qt.QGLFormat(qt.QGL.SampleBuffers), parent)
+        _BaseOpenGLWidget.__init__(self, parent)
         if 1:
             self.__test = None
         else:
@@ -947,14 +956,14 @@ def setupViewport(self, width, height):
         def renderText(self,  x, y, z, text, font = None, listbase = 2000):
             GL.glGetError()
             GL.glGetError()
-            qt.QGLWidget.renderText(self, x, y, z, text, font, listbase)
+            _BaseOpenGLWidget.renderText(self, x, y, z, text, font, listbase)
             GL.glGetError()
             GL.glGetError()
 
     def renderText(self, x, y, z, text, font = None, listbase = 2000):
         if font is None: font=self.font()
         if (QTVERSION < '4.3.2') or (QTVERSION > '4.4.0'):
-            qt.QGLWidget.renderText(self, x, y, z, text, font, listbase)
+            _BaseOpenGLWidget.renderText(self, x, y, z, text, font, listbase)
         else:
             if 0:
                 GL.glRasterPos3d(x, y, z)
@@ -1396,7 +1405,7 @@ def print3D(self):
     def closeEvent(self, event):
         self.__cacheTexture.openGLCleanup()
         self.setCacheEnabled(False)
-        qt.QGLWidget.closeEvent(self, event)
+        _BaseOpenGLWidget.closeEvent(self, event)
 
 if __name__ == '__main__':
     import sys

```

**Comment by vasole** [comment]
It should be closed by #209.

**Comment by vasole** [comment]
I had to revert the merge with #210

It seems the two widgets are not fully equivalent (setAutoBufferSwap, updateGL).

**Comment by PiRK** [comment]
Sorry about that, I missed a large part of the patching done in silx. 

There are two additional levels of wrapping in https://github.com/silx-kit/silx/blob/master/silx/gui/_glutils/OpenGLWidget.py : 

- _OpenGLWidget inherits  _BaseOpenGLWidget
- OpenGLWidget is composed based on  _OpenGLWidget

Unfortunately I cannot see any patching done for the methods you mention  (setAutoBufferSwap, updateGL).

**Comment by vasole** [comment]
Finally only minor modifications were required

- updateGL replaced by update
- buffer swapping not required
