### ISSUE TITLE
[bug] Batch fitting broken in 5.3.0

### ISSUE THREAD

**Issue by tschoonj** [vasole/pymca#212]
Hi Armando,

Our beamline staff ran into trouble when running the Batch fitting dialog in 5.3.0 (with the NexusTools.py patch applied).

Two screenshots that will hopefully provide you with some information:

![image001](https://user-images.githubusercontent.com/65736/39055767-eee31b14-44ac-11e8-9920-d3273dd25713.png)

![error](https://user-images.githubusercontent.com/65736/39055785-ff0624aa-44ac-11e8-9c80-ed450207a988.png)

Many thanks in advance for looking into this!

**Comment by vasole** [comment]
Problem reproduced. I will solve it as soon as possible. I guess a 5.3.1 release is needed.

**Comment by vasole** [comment]
It should be closed by #213 (already merged into master branch). Sorry.

I will have to inform you about how to properly write the HDF5 files in order to automatically read the live time and the calibration from the files.

**Comment by tschoonj** [comment]
Many thanks Armando for your quick fix! I will patch our installation right away

Have a great weekend,

Tom

**Comment by vasole** [comment]
@t20100 Please close the issue yourself if problem solved at your side.

**Comment by vasole** [comment]
@tschoonj Please close the issue yourself if problem solved at your side.

**Comment by tschoonj** [comment]
Sorry, forgot to do so.

Thanks again!
