### ISSUE TITLE
bunch of files with no licenses header and copyright owner

### ISSUE THREAD

**Issue by picca** [vasole/pymca#22]
Hello Armando,

I am preparing the pymca5 package. So once again Ineed to do the license check.
Since I will create new binary package

python3-pymca5 etc... this package will be reviewed by the ftpmaster team.
They are using this tool also to check for non free files.

So could you fix all these files.  This will ease the review at the end.

thanks

Frederic

picca@mordor:~/Debian/main/pymca/pymca$ licensecheck -r . | grep UNKN
./PyMca5/PyMcaGraph/ctools/_ctools/cython/MinMax.pyx: *No copyright* UNKNOWN
./PyMca5/PyMcaGraph/ctools/_ctools/cython/_ctools.py: *No copyright* UNKNOWN
./PyMca5/PyMcaGraph/ctools/_ctools/cython/InsidePolygonWithBounds.pyx: *No copyright* UNKNOWN
./PyMca5/PyMcaGraph/ctools/_ctools/cython/_ctools.pyx: *No copyright* UNKNOWN
./PyMca5/PyMcaGraph/ctools/_ctools/cython/ColormapLUT.pyx: *No copyright* UNKNOWN
./PyMca5/PyMcaGraph/ctools/_ctools/include/MinMax.h: *No copyright* UNKNOWN
./PyMca5/PyMcaGraph/ctools/_ctools/include/ColormapLUT.h: *No copyright* UNKNOWN
./PyMca5/PyMcaGraph/ctools/_ctools/include/InsidePolygonWithBounds.h: *No copyright* UNKNOWN
./PyMca5/PyMcaGraph/ctools/_ctools/setup.py: *No copyright* UNKNOWN
./PyMca5/PyMcaGraph/ctools/_ctools/src/InsidePolygonWithBounds.c: *No copyright* UNKNOWN
./PyMca5/PyMcaGraph/ctools/_ctools/src/MinMaxImpl.c: *No copyright* UNKNOWN
./PyMca5/PyMcaGraph/ctools/_ctools/src/ColormapLUT.c: *No copyright* UNKNOWN
./PyMca5/PyMcaGraph/ctools/__init__.py: *No copyright* UNKNOWN
./PyMca5/Object3D/Object3DQhull/Object3DQhull.c: *No copyright* UNKNOWN
./PyMca5/Object3D/Object3DCTools/MarchingCubes.c: *No copyright* UNKNOWN
./PyMca5/Object3D/Object3DCTools/setup.py: *No copyright* UNKNOWN
./PyMca5/Object3D/Object3DCTools/marchingsource.cpp: *No copyright* UNKNOWN
./PyMca5/Object3D/__init__.py: *No copyright* UNKNOWN
./PyMca5/EPDL97/GenerateEADLShellNonradiativeRates.py: *No copyright* UNKNOWN
./PyMca5/EPDL97/EADLParser.py: *No copyright* UNKNOWN
./PyMca5/EPDL97/EPDL97Parser.py: *No copyright* UNKNOWN
./PyMca5/EPDL97/GenerateEPDL97TotalCrossSections.py: *No copyright* UNKNOWN
./PyMca5/EPDL97/GenerateEADLBindingEnergies.py: *No copyright* UNKNOWN
./PyMca5/EPDL97/EADLSubshells.py: *No copyright* UNKNOWN
./PyMca5/EPDL97/GenerateEADLShellRadiativeRates.py: *No copyright* UNKNOWN
./PyMca5/EPDL97/__init__.py: *No copyright* UNKNOWN
./PyMca5/EPDL97/GenerateEADLShellConstants.py: *No copyright* UNKNOWN
./PyMca5/EPDL97/GenerateEPDL97CrossSections.py: *No copyright* UNKNOWN
./PyMca5/PyMcaIO/specfile/setup.py: *No copyright* UNKNOWN
./PyMca5/PyMcaIO/edf/setup.py: *No copyright* UNKNOWN
./PyMca5/PyMcaIO/sps/setup.py: *No copyright* UNKNOWN
./PyMca5/PyMcaIO/sps/Include/sps.h: UNKNOWN
./PyMca5/PyMcaIO/sps/Include/blissmalloc.h: UNKNOWN
./PyMca5/PyMcaIO/sps/Include/spec_shm.h: UNKNOWN
./PyMca5/PyMcaIO/sps/Src/sps.c: UNKNOWN
./PyMca5/PyMcaIO/sps/Src/sps_py.c: UNKNOWN
./PyMca5/PyMcaIO/MEDFile.py: UNKNOWN
./PyMca5/PyMcaGui/misc/QIPythonWidget.py: *No copyright* UNKNOWN
./PyMca5/PyMcaPlugins/CalculationThread.py: *No copyright* UNKNOWN
./PyMca5/PyMcaMath/mva/Lanczos.py: UNKNOWN
./PyMca5/PyMcaMath/mva/py_nnma/setup.py: *No copyright* UNKNOWN
./PyMca5/PyMcaMath/mva/py_nnma/nnma.py: UNKNOWN
./PyMca5/PyMcaMath/mva/py_nnma/__init__.py: *No copyright* UNKNOWN
./PyMca5/PyMcaMath/mva/NNMAModule.py: UNKNOWN
./PyMca5/PyMcaMath/PyMcaSciPy/signal/mediantools.c: UNKNOWN
./PyMca5/PyMcaMath/PyMcaSciPy/signal/median.py: *No copyright* UNKNOWN
./PyMca5/PyMcaMath/PyMcaSciPy/signal/medianfilter.c: *No copyright* UNKNOWN
./PyMca5/PyMcaMath/PyMcaSciPy/signal/__init__.py: *No copyright* UNKNOWN
./PyMca5/PyMcaMath/linalg.py: UNKNOWN
./PyMca5/PyMcaMath/sift/interpolation.py: *No copyright* UNKNOWN
./PyMca5/PyMcaMath/sift/sift.py: *No copyright* UNKNOWN
./PyMca5/PyMcaMath/sift/param.py: *No copyright* UNKNOWN
./PyMca5/PyMcaMath/sift/__init__.py: *No copyright* UNKNOWN

**Comment by vasole** [comment]
- The whole EPDL97 stuff is "public domain" as specified in the LICENSE file accompanying the module.
If that is a problem, I can change to MIT that is the closest thing to it but with a copyright.
- The marchingcubes code is public domain as specified in the source code.
- The whole PyMcaScipy module follows SciPy license as specified in accompanying LICENSE file.
- The linalg.py moduleis properly identified in the source code.

**Comment by vasole** [comment]
For the others I have made more explicit the conditions.

**Comment by vasole** [comment]
The PyMcaIO/sps module license is MIT. The copyright is shared between Certified Scientific Software and the ESRF.

**Comment by vasole** [comment]
Please let me know if with last commits I can close this issue.

**Comment by picca** [comment]
Hello armando, I am working on the 5.0.1 packaging.

it seems to me thaht there is a probleme with the Object3D modules
all files are lgpl2 except the __init__.py this is not very consistant.

Object3D/Object3DMovement.py: LGPL (v2 or later)
Object3D/GLWidgetCachePixmap.py: LGPL (v2 or later)
Object3D/SceneControl.py: LGPL (v2 or later)
Object3D/SceneGLWindow.py: LGPL (v2 or later)
Object3D/Object3DPrivateConfig.py: LGPL (v2 or later)
Object3D/Object3DCoordinates.py: LGPL (v2 or later)
Object3D/Object3DColormap.py: LGPL (v2 or later)
Object3D/SceneCoordinates.py: LGPL (v2 or later)
Object3D/Object3DSlider.py: LGPL (v2 or later)
Object3D/Object3DProperties.py: LGPL (v2 or later)
Object3D/Object3DIcons.py: LGPL (v2 or later)
Object3D/SceneGLWidget.py: LGPL (v2 or later)
Object3D/SceneWidget.py: LGPL (v2 or later)
Object3D/Object3DFileDialogs.py: LGPL (v2 or later)
Object3D/Object3DScene.py: LGPL (v2 or later)
Object3D/ClippingPlaneConfiguration.py: LGPL (v2 or later)
Object3D/Object3DPrintPreview.py: LGPL (v2 or later)
Object3D/Object3DBase.py: LGPL (v2 or later)
Object3D/Scene.py: LGPL (v2 or later)
Object3D/GLToolBar.py: LGPL (v2 or later)
Object3D/Object3DConfig.py: LGPL (v2 or later)
Object3D/HorizontalSpacer.py: LGPL (v2 or later)
Object3D/Object3DDirs.py: LGPL (v2 or later)
Object3D/setup.py: LGPL (v2 or later)
Object3D/ObjectTree.py: LGPL (v2 or later)
Object3D/Object3DRedBookFont.py: LGPL (v2 or later)
Object3D/SceneTree.py: LGPL (v2 or later)
Object3D/cx_setup.py: LGPL (v2 or later)
Object3D/SceneManager.py: LGPL (v2 or later)
Object3D/__init__.py: MIT/X11 (BSD like)
Object3D/VerticalSpacer.py: LGPL (v2 or later)
Object3D/PrivateConfigTools.py: LGPL (v2 or later)
Object3D/Object3DQt.py: LGPL (v2 or later)

**Comment by picca** [comment]
I have no information about this file

./PyMca5/Object3D/Object3DQhull/Object3DQhull.c: No copyright UNKNOWN

**Comment by picca** [comment]
I need also the whole PyMcaData data files licenses.
I know this is something really boring, but I got a package rejected due to this sort of data files.

**Comment by vasole** [comment]
On 06/03/2015 20:13, picca wrote:
>
> I need also the whole PyMcaData data files licenses.
> I know this is something really boring, but I got a package rejected 
> due to this sort of data files.
>
> —
>

For the issues related to the Object3D module, everything should be fine 
now. Probably it will change later on to MIT because it is going to be 
re-written, but for the time being it is simpler to leave it as LGPL.

For the data files, they are public domain. On some of them I could put 
a header but on others not. Where should I put the information?

Armando

**Comment by picca** [comment]
PyMcaGraph/ctools/_ctools/include/MinMax.h: *No copyright* UNKNOWN
PyMcaGraph/ctools/_ctools/include/ColormapLUT.h: *No copyright* UNKNOWN
PyMcaGraph/ctools/_ctools/include/InsidePolygonWithBounds.h: *No copyright* UNKNOWN

it seems that this should be MIT but I am not sure for all these files

**Comment by picca** [comment]
For the data,it seems that they were generated using some public databases,but I did not found the internet link explaining clearly the licenses :(((

**Comment by vasole** [comment]
On 06/03/2015 21:09, picca wrote:
>
> PyMcaGraph/ctools/_ctools/include/MinMax.h: /No copyright/ UNKNOWN
> PyMcaGraph/ctools/_ctools/include/ColormapLUT.h: /No copyright/ UNKNOWN
> PyMcaGraph/ctools/_ctools/include/InsidePolygonWithBounds.h: /No 
> copyright/ UNKNOWN
>
> it seems that this should be MIT but I am not sure for all these files
>

Yes, they are MIT. I have added it now.

**Comment by vasole** [comment]
On 06/03/2015 21:11, picca wrote:
>
> For the data,it seems that they were generated using some public 
> databases,but I did not found the internet link explaining clearly the 
> licenses :(((
>

As far as I know, published data on scientific journals are not copyrighted.

Armando

**Comment by picca** [comment]
this one is missing

PyMcaGui/misc/QIPythonWidget.py

**Comment by vasole** [comment]
Corrected.

**Comment by picca** [comment]
PyMcaIO/specfile/setup.py: *No copyright* UNKNOWN
PyMcaIO/sps/Include/sps.h: UNKNOWN
PyMcaIO/sps/Include/blissmalloc.h: UNKNOWN
PyMcaIO/sps/Include/spec_shm.h: UNKNOWN
PyMcaIO/sps/Src/sps.c: UNKNOWN
PyMcaIO/sps/Src/sps_py.c: UNKNOWN

it would be nice to add the MIT in the sps part

PyMcaIO/MEDFile.py: UNKNOWN

I now this one but the program does not recognize it. Is it possible to see what is the problem ?


PyMcaMath/mva/Lanczos.py: UNKNOWN
PyMcaMath/mva/py_nnma/setup.py: *No copyright* UNKNOWN
PyMcaMath/mva/py_nnma/nnma.py: UNKNOWN
PyMcaMath/mva/py_nnma/__init__.py: *No copyright* UNKNOWN
PyMcaMath/mva/NNMAModule.py: UNKNOWN
PyMcaMath/PyMcaSciPy/signal/mediantools.c: UNKNOWN
PyMcaMath/PyMcaSciPy/signal/median.py: *No copyright* UNKNOWN
PyMcaMath/PyMcaSciPy/signal/medianfilter.c: *No copyright* UNKNOWN
PyMcaMath/PyMcaSciPy/signal/__init__.py: *No copyright* UNKNOWN
PyMcaMath/linalg.py: UNKNOWN

I know a few, but would it be possible to fix the header in order to be able to be recognize by licensecheck ?

**Comment by picca** [comment]
PyMcaPlugins/CalculationThread.py: *No copyright* UNKNOWN ;)

**Comment by vasole** [comment]
On 06.03.2015 21:57, picca wrote:
> PyMcaIO/specfile/setup.py: _No copyright_ UNKNOWN
>  PyMcaIO/sps/Include/sps.h: UNKNOWN
>  PyMcaIO/sps/Include/blissmalloc.h: UNKNOWN
>  PyMcaIO/sps/Include/spec_shm.h: UNKNOWN
>  PyMcaIO/sps/Src/sps.c: UNKNOWN
>  PyMcaIO/sps/Src/sps_py.c: UNKNOWN
> 

The sps stuff it has the copyright and the license (text of the MIT). 
What's the problem???

> it would be nice to add the MIT in the sps part
> 
> PyMcaIO/MEDFile.py: UNKNOWN
> 
> I now this one but the program does not recognize it. Is it possible
> to see what is the problem ?

I see two possibilities:

- It says BSD but it misses the version?
- With so many BSD versions, the text corresponds to MIT.


> 
> PyMcaMath/mva/Lanczos.py: UNKNOWN
>  PyMcaMath/mva/py_nnma/setup.py: _No copyright_ UNKNOWN
>  PyMcaMath/mva/py_nnma/nnma.py: UNKNOWN
>  PyMcaMath/mva/py_nnma/INIT.py: _No copyright_ UNKNOWN
>  PyMcaMath/mva/NNMAModule.py: UNKNOWN
> 
> I know a few, but would it be possible to fix the header in order to
> be able to be recognize by licensecheck ?
> 

How can I install that on my system? To me that thing is buggy because 
those files do have a license and a copyright.

These other files do not have the information although they are 
accompanied by a LICENSE file.

>  PyMcaMath/PyMcaSciPy/signal/mediantools.c: UNKNOWN
>  PyMcaMath/PyMcaSciPy/signal/median.py: _No copyright_ UNKNOWN
>  PyMcaMath/PyMcaSciPy/signal/medianfilter.c: _No copyright_ UNKNOWN
>  PyMcaMath/PyMcaSciPy/signal/INIT.py: _No copyright_ UNKNOWN
>  PyMcaMath/linalg.py: UNKNOWN


Armando

**Comment by vasole** [comment]
On 06.03.2015 22:07, picca wrote:
> PyMcaPlugins/CalculationThread.py: _No copyright_ UNKNOWN ;)
> 

OK. It is longer the license than the code :)

**Comment by vasole** [comment]
It passes licensecheck.

**Comment by vasole** [comment]
Hi Fred,

I have noticed an issue with licensecheck that was originating false 
issues. For instance, the problem with the sps related modules was that 
the number of spaces following the comment symbol was more than what 
licensecheck expected. I think that should have been handled by it. Just 
reducing the number of spaces to 1 solved the "problem".

Armando

**Comment by picca** [comment]
can you report the bug with reportbug

the process is simple

reportbug devscripts

then follow the instruction :)

put [licensecheck] in the title of the bug report.


Cheers

Fred
