### ISSUE TITLE
[doc] Table of contents handling

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#222]
- There are things from the old web site (still at http://pyma.sourceforge.net) that I do not manage to reproduce like having control over the Table of Contents on the left at the welcome page.

-  I get warnings about things not being included in any toc tree:

![image](https://user-images.githubusercontent.com/5636251/39290697-cc5b444e-4930-11e8-957f-04b7673da2a7.png)

**Comment by PiRK** [comment]
To have the TOC in the side bar, the following patch seems to help:
```
diff --git a/doc/source/conf.py b/doc/source/conf.py
index 5019a1d..c402b87 100644
--- a/doc/source/conf.py
+++ b/doc/source/conf.py
@@ -148,7 +148,7 @@
 #html_use_smartypants = True
 
 # Custom sidebar templates, maps document names to template names.
-#html_sidebars = {}
+html_sidebars = {'**': ['globaltoc.html', 'relations.html', 'sourcelink.html', 'searchbox.html']}
 
 # Additional templates that should be rendered to pages, maps page names to
 # template names.
diff --git a/doc/source/index.rst b/doc/source/index.rst
index 193d2d8..7b9834e 100644
--- a/doc/source/index.rst
+++ b/doc/source/index.rst
@@ -27,7 +27,7 @@ The current version features:
 - Common data reduction operation (normalization, fitting, ...)
 
 .. toctree::
-   :hidden:
+   :maxdepth: 1
 
    overview.rst
    install.rst

```

Unfortunately it seems that the TOC must be visible in the main index page to be automatically displayed in the sidebar. Also, this makes the same TOC appear in all pages of the documentation, so we lose the local TOC.
