### ISSUE TITLE
it seems that there is a waring when I start pymca

### ISSUE THREAD

**Issue by picca** [vasole/pymca#23]
I do not know where this comming from but it is better to know that somethig is deprecated :)

picca@mordor:~/Debian/main/pymca$ pymca
/usr/lib/python2.7/dist-packages/sklearn/pls.py:7: DeprecationWarning: This module has been moved to cross_decomposition and will be removed in 0.16
  "removed in 0.16", DeprecationWarning)

**Comment by vasole** [comment]
On 07.02.2015 19:17, picca wrote:
> I do not know where this comming from but it is better to know that
> somethig is deprecated :)
> 

What Debian version? I do not get that message either on Debian 6 nor 
Debian 7.

Armando

**Comment by picca** [comment]
Debian8 :)

**Comment by vasole** [comment]
I do not directly use scikit learn. Probably has to do with MDP using it. Do you get that message from the python prompt by typing "import mdp"? MDP is not a critical component of PyMca and can be dropped.

**Comment by vasole** [comment]
Confirmed. It is a warning when importing mdp. The problem is to be solved at the mdp side. In case of mdp not being available, PyMca is still functional.
