### ISSUE TITLE
when I close pymca I get an assertion

### ISSUE THREAD

**Issue by picca** [vasole/pymca#24]
picca@mordor:~/Debian/main/pymca$ pymca
/usr/lib/python2.7/dist-packages/sklearn/pls.py:7: DeprecationWarning: This module has been moved to cross_decomposition and will be removed in 0.16
  "removed in 0.16", DeprecationWarning)
WARNING: fisx features not available
python: malloc.c:4157: malloc_consolidate: Assertion `p->bk_nextsize->fd_nextsize == p' failed.
Abandon

**Comment by vasole** [comment]
Is it reproducible? I do not get that error.
