### ISSUE TITLE
Deprecation warning when loading stack of EDF files

### ISSUE THREAD

**Issue by PiRK** [vasole/pymca#247]
```
/users/knobel/.local/lib/python2.7/site-packages/PyMca5/PyMcaIO/EdfFile.py:649: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  datatype)
```

It seems to be related to a recent numpy update: https://github.com/numpy/numpy/pull/9487 

> The rationale is that "string" means "unicode" in the brave new py3k world, and viewing unicode as binary is nonsensical.

Hundreds of warnings are printed.

**Comment by vasole** [comment]
CClosed by #248
