### ISSUE TITLE
[GUI] after SimpleFit, MCA and Scan plot unzoom

### ISSUE THREAD

**Issue by PiRK** [vasole/pymca#249]
If I zoom on a region and perform a simple fit, the zoom resets in the main window.

**Comment by PiRK** [comment]
I think the behavior is the same on the master branch. Maybe this is the intended behavior?

**Comment by vasole** [comment]
As far it respects the autoscale settings it is not a big problem.

I leave it up to you if to keep the previous settings or not.

**Comment by PiRK** [comment]
If it is not a regression on the silx branch compared to the master, I'll will but it at the bottom of my todo list. As you say, it is not a big problem, but I find it surprising.
