### ISSUE TITLE
Problem when I play with the OpenGL "onglet"

### ISSUE THREAD

**Issue by picca** [vasole/pymca#25]
for infor my graphic card is OpenGL 1.x only

picca@mordor:~/Debian/main/pymca$ pymca
/usr/lib/python2.7/dist-packages/sklearn/pls.py:7: DeprecationWarning: This module has been moved to cross_decomposition and will be removed in 0.16
  "removed in 0.16", DeprecationWarning)
WARNING: fisx features not available
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/PyMca5/PyMcaGui/io/QEdfFileWidget.py", line 682, in widgetSignal
    self.graph.removeImage()
TypeError: removeImage() takes at least 2 arguments (1 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/PyMca5/PyMcaGui/io/QEdfFileWidget.py", line 682, in widgetSignal
    self.graph.removeImage()
TypeError: removeImage() takes at least 2 arguments (1 given)
WRITE DOMAIN RELOC FAILURE 0x1 6 4
WRITE DOMAIN RELOC FAILURE 0x1 6 4
python: ../../../../../../../src/mesa/drivers/dri/radeon/radeon_fbo.c :451 : radeon_unmap_renderbuffer:  l'assertion « ok » a échoué.
Abandon

**Comment by vasole** [comment]
The removeImage error is solved now, but has nothing to do with OpenGL.
The OpenGL TAB currently uses OpenGL 1.x, so that should not be an issue unless your support is just OpenGL 1.1

What steps do you follow to get the message?
