### ISSUE TITLE
[doc] Plugin documentation not accessible without a search

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#250]
I did not find a clear way to reach the plugin documentation other than using the search box.

**Comment by PiRK** [comment]
I admit that the current way is complex : Tutorials and sample code -> Customizing PyMca -> 1D/stack Plugins -> Builtin Plugins

I'm thinking that builtin plugins could be documented in a standard user documentation section, rather than in "Customizing PyMca".

**Comment by vasole** [comment]
What about Customizing PyMca a at top level? It is just an idea.

- Customizing PyMca
  - Settings- 
   - Plugins    
    - XRF

**Comment by vasole** [comment]
Closed by #256
