### ISSUE TITLE
[pymcaroitool] segfault when opening a slave stack with PyQt5

### ISSUE THREAD

**Issue by PiRK** [vasole/pymca#266]
With PyQt5 (Qt 5.3.2) on my Debian 8 workstation, I get a Segmentation Fault when trying to open a second stack. 

After some debugging, I found that it seems to happen while instantiating the slave `QStackWidget()`. When I debug with pdb, it seems to happen in the first few lines of `QStackWidget()._buildBottom`, but not always on the same line.

It does not happen with PyQt4.

**Comment by PiRK** [comment]
It seems to be OK with the silx branch.

**Comment by vasole** [comment]
closed by #274
