### ISSUE TITLE
Legends widget does not show at side of plot when widget is wider than taller

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#277]
In PyMca, the legends widget was showing at the side of the plot when the later was wider than taller.

That is not the case now.  To test:

``python -m PyMca5.PyMca.McaAdvancedFit .\PyMca5\PyMcaData\Steel.spe```

One gets:

![image](https://user-images.githubusercontent.com/5636251/42595859-d714a81c-8553-11e8-883b-360f6d4e872d.png)

Instead of:

![image](https://user-images.githubusercontent.com/5636251/42595877-e90a824e-8553-11e8-8b7e-23312234dfc3.png)

**Comment by vasole** [comment]
@t20100 

Why is silx imposing to have the width twice the height and to be more than 1000 wide in pixels instead of just the 1.20 factor PyMca was using? A lot of people are using portable computers and not huge desktop screens.

**Comment by PiRK** [comment]
The silx condition for initializing the first dock widget on the right side is `width > (2.0 * height) and width > 1000`, whereas the PyMca condition was `w > (1.25 * h)`

**Comment by t20100** [comment]
This apparently has been changed while refurbishing PlotWindow 2 years ago...
The condition can easily be changed.
