### ISSUE TITLE
CentOS6  'QPainterPath' object has no attribute 'translate'

### ISSUE THREAD

**Issue by jangobash** [vasole/pymca#32]
When I start pymca on a CentOS6 (2.6.32-431.29.2.el6.x86_64) system, I get the following error messages.

###
$pymca

#the GUI start popup appears for abt. 1sec, then quits and there are the following messages in the terminal:

Traceback (most recent call last):
  File "./pymca", line 10, in <module>
    execfile(fname)
  File "/usr/lib64/python2.6/site-packages/PyMca5/PyMcaGui/pymca/PyMcaMain.py", line 163, in <module>
    from PyMca5.PyMcaGui.pymca import ScanWindow
  File "/usr/lib64/python2.6/site-packages/PyMca5/PyMcaGui/pymca/ScanWindow.py", line 44, in <module>
    from PyMca5.PyMcaGui.plotting import PlotWindow
  File "/usr/lib64/python2.6/site-packages/PyMca5/PyMcaGui/plotting/PlotWindow.py", line 43, in <module>
    from . import LegendSelector
  File "/usr/lib64/python2.6/site-packages/PyMca5/PyMcaGui/plotting/LegendSelector.py", line 80, in <module>
    Symbols['x'].translate(qt.QPointF(-0.5,-0.5))
AttributeError: 'QPainterPath' object has no attribute 'translate'
###

The installation was without error messages and dependencies should be met. 
Any idea?

Thanks 
Jan

**Comment by vasole** [comment]
Are you using latest PyMca release or current master branch? I guess with current master the error will still be there but the application will not crash.

Does anything change if you start PyMca as "pymca -f"

**Comment by vasole** [comment]
The translate method is present in Qt4 and Qt5:

- http://doc.qt.io/qt-4.8/qpainterpath.html
- http://doc.qt.io/qt-5/qpainterpath.html

Please check the version of Qt PyMca is using via the help menu -> About Qt

**Comment by vasole** [comment]
According to the Qt documentation in previous links:

- This function was introduced in Qt 4.6.

If your Qt version is older that would explain your problem.

**Comment by jangobash** [comment]
python -c "import PyQt4.Qt as qt; print(qt.qVersion())" or
"yum info Qt" says version 4.6.2 
"yum info PyQt" says version 3.18.1 (if relevant here)

pymca -f shows the same behaviour.

I installed from here https://sourceforge.net/projects/pymca/ yesterday.

**Comment by vasole** [comment]
What is relevant is the Qt version (you seem to have 4.6.2 so the method should be there) **and** the PyQt4 version because PyMca does not use PyQt(3) any longer. If you are using a PyQt4 version released prior to the release of Qt 4.6 you will be missing that functionality.

To get the PyQt version you can do:

python -c "import PyQt4.Qt as qt; print(qt.PYQT_VERSION_STR)"

**Comment by jangobash** [comment]
python -c "import PyQt4.Qt as qt; print(qt.PYQT_VERSION_STR)"   => 4.6.2
So I have no more ideas...

**Comment by vasole** [comment]
I still think is a problem with your PyQt4 version. At the python prompt type:

import PyQt4.Qt as qt
a = qt.QPainterPath()
dir(a)

You should see translate and translated among the available methods. If they are not there, the problem is your PyQt4 installation.

**Comment by jangobash** [comment]
Got it! translate is not implemented. As long as we do not want to bend the installation or simply update the system to CentOS7, we can only run PyMCA versions <5 I guess. 
Thanks for your investigations - Sincerely Jan

>>> dir(a)
['CurveToDataElement', 'CurveToElement', 'Element', 'ElementType', 'LineToElement', 'MoveToElement', '__add__', '__and__', '__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__iadd__', '__iand__', '__init__', '__ior__', '__isub__', '__le__', '__lt__', '__module__', '__mul__', '__ne__', '__new__', '__or__', '__radd__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__ror__', '__rsub__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__weakref__', 'addEllipse', 'addPath', 'addPolygon', 'addRect', 'addRegion', 'addRoundRect', 'addRoundedRect', 'addText', 'angleAtPercent', 'arcMoveTo', 'arcTo', 'boundingRect', 'closeSubpath', 'connectPath', 'contains', 'controlPointRect', 'cubicTo', 'currentPosition', 'elementAt', 'elementCount', 'fillRule', 'intersected', 'intersects', 'isEmpty', 'length', 'lineTo', 'moveTo', 'percentAtLength', 'pointAtPercent', 'quadTo', 'setElementPositionAt', 'setFillRule', 'simplified', 'slopeAtPercent', 'subtracted', 'subtractedInverted', 'toFillPolygon', 'toFillPolygons', 'toReversed', 'toSubpathPolygons', 'united']
>>>

**Comment by vasole** [comment]
Well, you could upgrade your PyQt4 version. The Qt version is correct, so you should not break anything.
