### ISSUE TITLE
[ROI Imaging] Provide Mask Scatter View Plugin

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#346]
The goal is to provide a way to deal with irregularly spaced stacks without having to rewrite the application.

Basically can work on a visualization based on point index and not any longer in dimension.

**Comment by PiRK** [comment]
I found some two year old code that cold be relevant : https://github.com/PiRK/scripts/blob/master/MaskScatterWidget.py

I will see how it can be adapted to all new silx scatter features.

**Comment by vasole** [comment]
Closed by #352
