### ISSUE TITLE
QTooltip color not showing correctly under Ubuntu 16.04

### ISSUE THREAD

**Issue by maurov** [vasole/pymca#35]
Hello,

The QTooltip is showing black on black background under Ubuntu 16.04. It would be nice to force a correct color. A patch to PyMcaMain could be :

`app.setStyleSheet("QToolTip { color: #ffffff; background-color: #2a82da; border: 1px solid white; }")`

**Comment by vasole** [comment]
I have forced the tooltip color in PyMcaMain.py and QStackWidget.py that are the two main applications.

Does it also happen with pymcapostbatch? (Usage pymcapostbatch or rgbcorrelator followed by the name of an EDF file). If it does not happen there, the problem is at my side. If it does not happen, then there is a problem with the support of your Ubuntu theme.

**Comment by maurov** [comment]
Thanks for forcing the black text on yellow background in PyMca main.

In pymcapostbatch it shows white text on black background, so those tools are not affected by this problem.

On the other hand, the tooltip of the IPython console that appears when showing the docstring of a function is affected by this black text on black background bug. I think it is related to PyMca because in SILX it shows correctly.

**Comment by vasole** [comment]
Thanks for testing. The only idea that comes to my mind at this moment is to get rid of the lines 129-138 in PyMca main where the application Palette is modified.Please, can you check if that is the origin of the problem?

**Comment by maurov** [comment]
No, commenting lines 129-138 of PyMcaMain does not help.

**Comment by vasole** [comment]
It seems it is not the first time things like that happen on some ubuntu themes:

 http://ubuntuforums.org/showthread.php?t=1580266

I will need access to your computer to figure out what can be triggering the problem.

**Comment by maurov** [comment]
Problem solved. I forced the tooltip background color with the `gnome-color-chooser` utility, as suggested here:

http://askubuntu.com/questions/45001/how-to-fix-black-tooltips-in-eclipse
