### ISSUE TITLE
[hdf5 silx] Two plots with images

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#360]
@PiRK 

With latest silx version, when selecting a 2D dataset, right click show information and then selecting the image view, one gets one additional Plot1D window besides the one on the DataView tab.

**Comment by PiRK** [comment]
I found it. The extra widget is the 2D plugin we put as an example (medfilt2DPlugin). And it opens because the plugin's `activeImageChanged` method is connected even if the plugin was never called before.

**Comment by vasole** [comment]
Great funding!
