### ISSUE TITLE
[QIPythonWidget] printText not working

### ISSUE THREAD

**Issue by maurov** [vasole/pymca#37]
`printText` method in `QIPythonWidget` is not working anymore. Tested with python 3.4 and 3.5, IPython 4.1.2 and 5.0.0

Any idea for an alternative method to push text to the console?

**Comment by vasole** [comment]
The method is there but it does nothing.

The best way to push text to the console seems to be to use custombanner keyword at instantiation.

**Comment by maurov** [comment]
Indeed. I close the ticket then.
