### ISSUE TITLE
error fisx_data directory

### ISSUE THREAD

**Issue by maurov** [vasole/pymca#40]
Hello,

After a recent update of PyMca (git version) I get the following error at start:

> Traceback (most recent call last):
>   File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "/home/mauro/local/py35/lib/python3.5/site-packages/PyMca5/__init__.py", line 36, in <module>
>     from fisx.DataDir import FISX_DATA_DIR
>   File "/home/mauro/local/py35/lib/python3.5/site-packages/fisx/DataDir.py", line 57, in <module>
>     raise IOError('%s directory not found' % basename)
> OSError: fisx_data directory not found

Any quick fix?

Thanks

**Comment by vasole** [comment]
pip install fisx

**Comment by vasole** [comment]
You can also try apt-get install fisx (it is available as an official debian package since a bit more than one month)

**Comment by vasole** [comment]
It seems you already have fisx installed....

Try to install PyMca adding --fisx to your PyMca setup.py installation call.
 
python setup.py install --user --fisx

**Comment by maurov** [comment]
Hello,

Initially, I was installing fisx via PyMca

`python setup.py install --user --fisx`

But this gave me the error... so I decided to clean fisx installation and install it via `pip install fisx`.

Now works, so I think the best way to install fisx is via pip.

I close the ticket, thanks.
