### ISSUE TITLE
[fast XRF fit] Name of NXprocess group

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#419]
I guess instead of generating a group with the default name images, a name actually indicating what the process was seems more appropriate. Something like fast_xrf_fit, fast_xrf_analysis, xrf_fit, ...

To be discussed.

**Comment by woutdenolf** [comment]
So the default, which is currently IMAGES.h5::/images/images, should be IMAGES.h5::/images/fast_xrf_fit?

**Comment by vasole** [comment]
Yes, it is a good possibility. At the DAU we try to highlight the actual process performed as name of the NXprocess group.

**Comment by vasole** [comment]
Closed by #420
