### ISSUE TITLE
[GUI] Read images from HDF5 files

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#422]
PyMca relies on EDF to read image data at several places. It is critical to be able to do the same from HDF5 files at least in the External Images plugins and the RGB correlator.

**Comment by woutdenolf** [comment]
As for the external images plugin, should I do something like this? @vasole 
```
class ExternalImagesStackPlugin(StackPluginBase)

    def _loadImageFiles(self):
        # prompt for files
        for filename in filelist:
            edf -> EdfFileDataSource -> StackPluginResultsWindow
            dat, csv -> specfilewrapper -> StackPluginResultsWindow
            h5 -> HDF5Stack1D -> StackPluginResultsWindow
            else -> QImage -> ExternalImagesWindow
```

**Comment by vasole** [comment]
- I fail to catch the need for the prompt keyword. I guess you can use HDF5Widget.getURI and accept URIs as filenames for single datasets and groups. Given the fact the RGB Correlator is a graphical application, it can always prompt for an URI in case of receiving just an HDF5File
- I would avoid the use of HDF5Stack1D for the external images. I find that class somewhat fragile. Is it really adapted to StackPluginResultsWindow? The later expects lists of images and not a stack of images. For browsing a stack, the StackBrowserPlugin uses StackBrowser that is more appropriate for browsing stacks.

**Comment by vasole** [comment]
Concerning the refactoring, I would avoid it and work just adding the HDF5 support with the minimal changes. Hopefully it will be the last added format.

**Comment by vasole** [comment]
Basically in addFileList one needs to check 

- if the file exists and if it is an HDF5 file to open and additional dialog to fetch the URI
- if the file does not exist check if we have got an URI

**Comment by woutdenolf** [comment]
I added HDF5 support to the RGB correlator and External Images Plugin. Any others?
