### ISSUE TITLE
Curve selection incomplete

### ISSUE THREAD

**Issue by kkummer** [vasole/pymca#426]
The new scan window does not allow to select curves that are plotted on the right axis, e.g. the derivative of a curve. As a result, it is not anymore possible to perform some actions like fitting a derivative. In the past it was possible to select curves plotted on the right axis via the legends widget.

**Comment by vasole** [comment]
Please, can you provide PyMca version and example data? I have just tested it and the legends widget allows to set the active curve despite being mapped to the right axis.

**Comment by vasole** [comment]
Just make sure you show the legends widget via Options -> Legends

**Comment by kkummer** [comment]
Thanks. That was the problem. I could not figure out how to show the legends. The options drop-down menu seems a little hidden even though it carries quite a lot of functionality.

**Comment by vasole** [comment]
OK.
