### ISSUE TITLE
Bug in PyMcaFileDialogs.py

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#43]
PyMcaFileDialogs.py uses a wrong syntax for QFileDialog.getOpenFileNamesAndFilter (PyQt4). According to http://pyqt.sourceforge.net/Docs/PyQt4/qfiledialog.html

Multiple filters are separated with ';;'. For instance:
"Images (.png .xpm .jpg);;Text files (.txt);;XML files (*.xml)

**Comment by schluenz** [comment]
thanks for the quick fix! fyi: I suspect PyMcaGui/pymca/PyMcaBatch.py and PyMcaGui/io/QSourceSelector.py have the same issue.
