### ISSUE TITLE
Timestamp as X-axis: show formatted date on mouse hover

### ISSUE THREAD

**Issue by bjoe2k4** [vasole/pymca#433]
I have got data that uses unix timestamps as x-axis. To conveniently know the time when something happened, i would like to convert this timestamp shown on mouseover (red box in attached picture) to a human readable string. Unfortunately I could not find the location in the code where these numbers are generated and formatted. Any point in the right direction would be appreciated.

![2019-03-161](https://user-images.githubusercontent.com/1668390/54475537-98a33000-47f2-11e9-8086-e0b28d62728c.png)

**Comment by vasole** [comment]
@t20100 

In silx we support the time axes. Have we already foreseen a toggle accessible from the user interface?

**Comment by vasole** [comment]
The widget can be recovered with ``getPositionInfoWidget()`` however, there is not a setter and one has to pass the converters on widget creation. The converters themselves can be recovered with getConverters, but again, there is no public API to change them after widget creation:

https://github.com/silx-kit/silx/blob/master/silx/gui/plot/tools/PositionInfo.py

The simplest solution I see for you at this point is to implement a Plugin1D that connects to the plot mouse signal and shows the translation at the mouse coordinates while the plugin is active.

**Comment by bjoe2k4** [comment]
Thanks for the quick answer. I have managed to write such a plugin that connects to mouse events and sets the current timestamp to the plot title. Not ideal, since i was lacking the API to add a moving widget to the plot, but works for me.

**Comment by vasole** [comment]
You could also display the text at the actual mouse cursor.

Something on the lines  of what I use at other parts of PyMca:

```python
def setMouseText(self, text=""):
        try:
            if len(text):
                qt.QToolTip.showText(self.cursor().pos(),
                                     text, self, qt.QRect())
            else:
                qt.QToolTip.hideText()
        except:
            _logger.warning("Error trying to show mouse text <%s>" % text)
```

**Comment by t20100** [comment]
In `silx`, there is so far no control of the date ticks from the GUI, and the `PositionInfoWidget` does not support it.

**Comment by bjoe2k4** [comment]
`setMouseText` will cause lots of flickering when triggered on `mouseMoved`, so i have changed the event to `mouseClicked` in the plugin and it works fine now. Thanks!

**Comment by vasole** [comment]
@bjoe2k4 

Please, feel free to send me your plugin. It can be of use to other people.
