### ISSUE TITLE
UnicodeDecodeError when opening OMNIC file on Linux

### ISSUE THREAD

**Issue by jat255** [vasole/pymca#447]
I am attempting to open an OMNIC .map FTIR file, but receiving an error when I attempt to do so on my Linux machines. 

```python
from PyMca5.PyMcaIO import OmnicMap
omnic_file = OmnicMap.OmnicMap(filename)

~/.conda/envs/test_env/lib/python3.7/site-packages/PyMca5/PyMcaIO/OmnicMap.py in __init__(self, filename)
     67         else:
     68             fid = open(filename, 'r')
---> 69         data = fid.read()
     70         fid.close()
     71

~/.conda/envs/test_env/lib/python3.7/codecs.py in decode(self, input, final)
    320         # decode input (taking the buffer into account)
    321         data = self.buffer + input
--> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
    323         # keep undecoded input until the next call
    324         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 290: invalid continuation byte
```

I am not sure what is ultimately causing this error, but if I change https://github.com/vasole/pymca/blob/master/PyMca5/PyMcaIO/OmnicMap.py#L68 to open the file as a binary (like specified for when running on a Window system, the file loads with no problem).

Any ideas?

**Comment by jat255** [comment]
I'll add I've tried this with three or four different `.map` files, and they all give the same error

**Comment by vasole** [comment]
Thanks. In fact your proposed change is all what is needed to fix the issue.

**Comment by jat255** [comment]
@vasole Great! Looks like maybe I stumbled upon an unnoticed bug that arose on the switch to Python 3.X, since that bit of code was last changed in 2007!

I've submitted a PR if you'd like to take a look.
