### ISSUE TITLE
[BatchFit] Replace spaces by underscores

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#483]
The NeXus rule is to use underscores. Therefore "Fe K" should become "Fe_K". To verify with old output files if "Fe_K" or "Fe-K" should be used.

**Comment by vasole** [comment]
To be consequent with the other output, we have to use the underscore.

**Comment by woutdenolf** [comment]
Ok, I'm on it

**Comment by vasole** [comment]
closed by #487
