### ISSUE TITLE
[Batch Fit] Chisquare image not generated

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#489]
The chisq image is missing among the generated EDF files not inside the .dat file

**Comment by woutdenolf** [comment]
This is only saved when `diagnostics` is enabled. Should I always save it? The `OutputBuffer` has a `diagnostics` property which enables/disables `saveFOM`, `saveResiduals`, `saveData`, `saveFit`. The first stands for figures-of-merit (currently contains chisq, nFreeParameters, nObservations). What I could do is make sure `saveFOM` is always set, no matter what the user selects in the GUI. But then you get all FOMs. Should I consider chisq separately?

**Comment by woutdenolf** [comment]
No sorry, that's for HDF5. For EDF and DAT, only the chisq is saved from the FOMs. But still only when `diagnostics` is enabled by the user.

**Comment by vasole** [comment]
In the past it was systematically saved.

**Comment by vasole** [comment]
closed by #500
