### ISSUE TITLE
[ROI Batch] Support command line and HDF5

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#510]
The ROI batch should evolve in an analogue way to the FastXRFLinearFit in the sense of accepting HDF5 files from the command line and generating HDF5 output.

**Comment by woutdenolf** [comment]
So basically this means using the `OutputBuffer` in `StackROIBatch`? Does it need to be done before the next release? And when is that release?

**Comment by vasole** [comment]
I do not think it is necessary for 5.5.0 (but certainly for 5.5.1).

I have to solve #479 and deal with #466 in order to make the 5.5.0

The problem is that silx 0.10.1 is already in debian experimental and that breaks PyMca.

**Comment by vasole** [comment]
Closed by #528
