### ISSUE TITLE
[CI] Tests not passing under windows and Python 3.8, h5py 2.9

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#521]
They are mainly HDF5 related tests.

![image](https://user-images.githubusercontent.com/5636251/60329136-07665c80-9990-11e9-8b8d-d31f032fb802.png)

**Comment by woutdenolf** [comment]
I installed python 3.8.0b1 but don't have wheels for numpy. I tried building from source but got errors. Also tried setting MSVC version manually without success:
 "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64 8.1 -vcvars_ver=15.9

Anyway, I think it is an h5py API change:
https://github.com/vasole/pymca/blob/dea4f6d10c03c0cf76d8468ab719cdaff11296fd/PyMca5/PyMcaIO/NexusUtils.py#L278

Try adding OSError:

```python
    except (RuntimeError, OSError):
```

**Comment by vasole** [comment]
You can download the relevant packages from

https://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by vasole** [comment]
I tried the above change without success. I think it is the handling of the temporary files.

**Comment by woutdenolf** [comment]
It fixes the issue for me (see PR, tested on window + py3.8).

**Comment by vasole** [comment]
It seems I did a mistake somewhere. It fixes the problem for me too. Thanks.
