### ISSUE TITLE
[PyMcaMath][linalg] issue when calling linalg.lstsq

### ISSUE THREAD

**Issue by payno** [vasole/pymca#535]
linalg.lst fails when inputs arrays are (1, 2) and (1,). This generate a numpy error

To reproduce:
``` python
from PyMca5.PyMca import linalg
import numpy

x = numpy.array([[1.00e+00, 3.96e+03]])
y = numpy.array([0.44951201, ])
linalg.lstsq(x, y, uncertainties=False, weight=False)
```

context: try to call 'normalize' for some random spectrum

**Comment by vasole** [comment]
I'm not really sure it makes sense to try to solve the matrix p in `x * p = y` with two parameters and only one point.
