### ISSUE TITLE
Saving and loading calibration file 

### ISSUE THREAD

**Issue by uljo1962** [vasole/pymca#537]
I have problems loading or saving calibration files in the 1D image stack window. The same occurs in the main MCA window. 

Regards,
Ulf

<class 'ValueError'> Non-existing directory <('D:/NanoMAX/visitors/20180313/2018121208/process/XRF_pymca_new>   File "C:\Program Files\PyMca 5.5.0\PyMca5\PyMcaGui\pymca\McaCalibrationControlGUI.py", line 214, in _savesignal
    PyMcaDirs.outputDir = os.path.dirname(filename)
  File "C:\Program Files\PyMca 5.5.0\PyMca5\PyMcaCore\PyMcaDirs.py", line 87, in __setattr__
    raise ValueError("Non-existing directory <%s>" % value)

<class 'ValueError'> Non-existing directory <('D:>   File "C:\Program Files\PyMca 5.5.0\PyMca5\PyMcaGui\pymca\McaCalibrationControlGUI.py", line 214, in _savesignal
    PyMcaDirs.outputDir = os.path.dirname(filename)
  File "C:\Program Files\PyMca 5.5.0\PyMca5\PyMcaCore\PyMcaDirs.py", line 87, in __setattr__
    raise ValueError("Non-existing directory <%s>" % value)

<class 'ValueError'> Non-existing directory <('C:/Users/ulfjoh/Documents>   File "C:\Program Files\PyMca 5.5.0\PyMca5\PyMcaGui\pymca\McaCalibrationControlGUI.py", line 214, in _savesignal
    PyMcaDirs.outputDir = os.path.dirname(filename)
  File "C:\Program Files\PyMca 5.5.0\PyMca5\PyMcaCore\PyMcaDirs.py", line 87, in __setattr__
    raise ValueError("Non-existing directory <%s>" % value)

**Comment by vasole** [comment]
#538 should solve the issue.

**Comment by vasole** [comment]
Having made a release just yesterday, I have uploaded to sourceforge a patched executable with the fix.

I invite you to download again the pymca5.5.0-win64.exe file in a couple of hours when the sourceforge mirrors should have realized the update. The new executable file is slightly bigger.
