### ISSUE TITLE
[Printing] Print preview does not respect print configuration

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#54]
When customizing printing, the space to be occupied in the page is not respected. It was working with PyMca 5.1.1

**Comment by PiRK** [comment]
It seems the feature was only implemented for  `printPreview.addSvgItem`, not for `printPreview.addPixmap`. 

Since https://github.com/vasole/pymca/commit/73f285f1480ac34461238b0755973fda09162a8e, `addSvgItem` is used only for Qt > 5.0.0.

**Comment by vasole** [comment]
We'll have to review that change then. The problem was that cropping of the SVG item was not working properly when data where zoomed.
