### ISSUE TITLE
can't open pymca after installation

### ISSUE THREAD

**Issue by XinFeng222** [vasole/pymca#589]
Hi
I installed pymca 5.5.0 on my laptop, but after installation is finished, I clicked open then a black screen pops out. I barely have time to read what is on before it dissappears itself. Anyone has the same issues? What I should do? Thanks!

**Comment by vasole** [comment]
I guess you speak about the frozen binary downloaded from sourceforge.
I assume you are using Windows (7? 10?)

Please open a command prompt window and  inside it execute the command

"C:\Program Files\PyMca 5.5.0\PyMcaMain.exe"

That way the message will stay.

**Comment by XinFeng222** [comment]
Thanks It works. after I execute the command, black command window stays, and also the PymCa interface shows up. But do you know what is happening? Why I could not be able to open the software by double clicking? the error msg is below:

C:\Progran Files\Pymca 5.5.0\pyopencl\_ _init_ _.py:43:UserWarning: It looks like you are importing PyOpenCL from its source directory. This likely won't work,
![screenshot](https://user-images.githubusercontent.com/55898321/65818981-4ea0fb00-e1d4-11e9-9d1e-a1b377ca843c.jpg)

**Comment by vasole** [comment]
Those warnings are harmless, they correspond to rarely used extensions.

If I have properly understood the program is running from the command prompt but not from the start menu.

If that is the case, it may sound stupid but have you tried to start it again from the start menu to see if you can still reproduce the crash? I do not see why it should work in one case and not in the other. The objective when asking you to start it from the prompt was to visualize the possible errors but you just have some warnings.

**Comment by XinFeng222** [comment]
No I tried from the start menu, it would not work. it is the same. that black command box shows then dissappears quickly. Mine is window 8. Is that why this is happening?

**Comment by vasole** [comment]
Please, try to install the VS2015 runtime from microsoft to see if it helps:

https://www.microsoft.com/en-US/download/details.aspx?id=48145

**Comment by XinFeng222** [comment]
now it works! Thank you very much!!! Although the warning msg appears again. I guess it has no harm?
![QQ截图20190929100752](https://user-images.githubusercontent.com/55898321/65835248-2d5a1080-e2a1-11e9-9050-039b169063da.jpg)

**Comment by vasole** [comment]
Yes, the warning is harmless. You are just missing a extension adding tomographic reconstruction capabilities.

**Comment by XinFeng222** [comment]
Thank you very much!
