### ISSUE TITLE
Bug in XMIMSIM-PyMca dialog

### ISSUE THREAD

**Issue by tschoonj** [vasole/pymca#61]
Hi Armando,

When  clicking either the first or second Browse button in the XMIMSIM-PyMca dialog, I get the following error:

````
QFileDialog.getOpenFileName(QWidget parent=None, QString caption=QString(), QString directory=QString(), QString filter=QString(), QString selectedFilter=None, QFileDialog.Options options=0): argument 5 has unexpected type 'NoneType'   File "C:\Program Files\PyMca 5.1.4\PyMca5\PyMcaGui\physics\xrf\XRFMCPyMca.py", line 87, in __browseList
    return self._browseList()
  File "C:\Program Files\PyMca 5.1.4\PyMca5\PyMcaGui\physics\xrf\XRFMCPyMca.py", line 161, in _browseList
    GetFileList._browseList(self, filetypes)
  File "C:\Program Files\PyMca 5.1.4\PyMca5\PyMcaGui\physics\xrf\XRFMCPyMca.py", line 106, in _browseList
    None)
````

I am trying to test if that old problem where the 64-bit version of `xmimsim-pymca` could not be spawned by PyMca is still present. It looks good though as I am able to generate the MC Matrix spectrum without problems. If the quantification also works properly I will retire the Windows 32-bit build of XMI-MSIM.

Thanks,

Tom

**Comment by vasole** [comment]
Hi Tom,

The problem with the 64 bit version was mainly when launching XMI-MSIM from the Advanced Fit Window (for instance by clicking on the MC Matrix Spectrum button).

I'll take a look at the other issue.

**Comment by tschoonj** [comment]
Thanks!
