### ISSUE TITLE
[GUI] Allow to copy table data to clipboard

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#68]
Requested for Motor Info and SPEC Scan Info widgets.

**Comment by PiRK** [comment]
For `MotorInfoTable`, this would be as simple as inheriting from `silx.gui.widgets.TableWidget.TableWidget`, or if the silx dependency is to be avoided for the moment, copy-paste the silx actions (`CopySelectedCellsAction,  CopyAllCellsAction`) and add them to the table widget.

Regarding SPEC Scan Info widgets, should the copy-paste only take the data in text entries, or also copy the labels?

**Comment by PiRK** [comment]
It was slightly more complicated than expected, because this selection mode had not been previously tested:   https://github.com/vasole/pymca/blob/master/PyMca5/PyMcaGui/io/SpecFileDataInfo.py#L127. 
I fixed this unexpected case also in silx (https://github.com/silx-kit/silx/pull/926)
