### ISSUE TITLE
Easiest way to adapt to our data format

### ISSUE THREAD

**Issue by alexbjorling** [vasole/pymca#691]
We have a basic hdf5 nexus-style (but not nexus) hdf5 format. The scanning positions are in length-N arrays, one for each axis, and the XRF spectra are stored in an array of shape (N, 4, M), where 4 is the number of channels on the xspress3 and M is the number of energy bins. There's also I0 values stored in the alba2 tree.

![image](https://user-images.githubusercontent.com/20105820/79219492-ac382480-7e52-11ea-8cda-cbd4b0268cb6.png)

What's the easiest way to streamline data loading? Adding some loader class to PyMca? If so how? Or writing a script that loads the data, creates a QStackWidget and attaches the data to it?

**Comment by vasole** [comment]
It is a very bad idea to mix all detectors in the same dataset. How do you want a code to figure out calibration and live time for each detector?

Each physical entity should have its own representation in order for the analysis codes not to have to guess anything. If you want to "save" your file try to create individual datasets for each detector using virtual data sets. I do not know if you will be able to do it. I have never tried to do it with an index in the middle.  

Please take a look at http://www.silx.org/doc/PyMca/dev/hdf5/index.html
It is not complete, but you will get an idea (particularly if you look at the code), about what can be automatically recognized by PyMca when loading. From those things, currently spectra, calibration, live time and positions are used.

As an additional comment, the measurement group approach purpose is to offer the interactive user a quick access to a flattened view of most relevant things measured. If you are going to put a rich structure inside, as you are doing, it defeats its purpose and it is preferable to use pure NeXus and to move your stuff into an NXinstrument group.

**Comment by alexbjorling** [comment]
I was not asking for a review of our data format. We are also not mixing
detectors in datasets, you must have misunderstood something. No code is
doing any guessing.

If there's no simple way to write a loader, we will have to continue
loading the hard way, with a lot of mouse clicking.

Den fre 17 apr. 2020 10:11V. Armando Solé <notifications@github.com> skrev:

**Comment by vasole** [comment]
Well, I understood you were putting four detectors into the same dataset. What are the 4 xpress channels?

**Comment by alexbjorling** [comment]
Yes. I consider the xspress3 one detector.

So it sounds like your answer to my question is to change the data format
to suit pymca?

Den fre 17 apr. 2020 10:22V. Armando Solé <notifications@github.com> skrev:

**Comment by vasole** [comment]
... but you actually have four elements with different physical parameters to be accounted for correct analysis. 

Never mind. I am not asking you to change your format to suit PyMca.

My way of thinking is that if acquisition saves things in a particular way that defeats any standard, there must be a good reason for it. If you have no reason, why not to change it, if you have a reason then keep reading.

My point is that there is no functionality difference between a loader and an HDF5 file made up of external links.

Nothing prevents you from building your own Stack object and send it to a QStackWidget. However, that will not be enough to allow batch fittings where the code will automatically account for different live times (implemented), photon fluxes (not implemented yet) or sample transmission (not implemented yet).

**Comment by vasole** [comment]
If all your interest is to eliminate the initial clicking and not a complete support, you just need to add several attributes to your groups and one attribute to your xpress3 dataset.

**Comment by alexbjorling** [comment]
> there is no functionality difference between a loader and an HDF5 file made up of external links
Well then the conversion is done at runtime, not as an extra step on disk. But I'll write a new set of files with links and virtual datasets. Where can I find a specification of the hdf5 structure to use?

**Comment by vasole** [comment]
For just eliminating clicks (you could easily add it to your current format)

```
whatever0@NX_class=u"NXentry"
whatever0/whatever4@NX_class=u"NXdata"  # this whatever group can be your measurement 
whatever0/whatever4@signal=u"name_of_your_soft_link_to_the xpress3 data"
whatever0/whatever4/name_of_your_soft_link_to_the_xpress3_data # soft link to the xpress3 data
```


For more or less complete support (@ represents attribute).

```
whatever0@NX_class=u"NXentry"
whatever0/whatever1@NX_class=u"NXinstrument"
whatever0/whatever1/whatever3@NX_class=u"NXdetector"
whatever0/whatever1/whatever3/data             # your data for that detector
whatever0/whatever1/whatever3/data@interpretation="spectrum" 
whatever0/whatever1/whatever3/live_time      # (optional, array of n spectra values) your live times
whatever0/whatever1/whatever3/calibration   # (optional, 3 floats array) your detector calibration
whatever0/whatever1/positioners@NX_collection # group containing all your motors (your n_point buffer)
whatever0/whatever4@NX_class=u"NXdata"  # this whatever group can be your measurement 
whatever0/whatever4@signal=u"name_of_your_soft_link"
whatever0/whatever4/name_of_your_soft_link # soft link to the detector data
```

**Comment by vasole** [comment]
The simplest way to adapt your format is to create a virtual dataset per detector element.
It does not need to be an external file since it can be created at acquisition time since virtual datasets can take place within the same file.
