### ISSUE TITLE
[RGB] scatter plot

### ISSUE THREAD

**Issue by woutdenolf** [vasole/pymca#729]
When doing a 2D XRF map with ROI counters (saved as flat datasets) it is currently not possible to open them in RGB correlator.

**Comment by vasole** [comment]
Do you have an example? The RGB correlator allows to reshape 1D data.

**Comment by woutdenolf** [comment]
/data/id21/inhouse/20Sep/blc12369/id21/fluoXAS/fluoXAS_0001/fluoXAS_0001.h5

Take any l2scan. For me the RGB correlator window only allows me to select one dataset at a time and the reshape box does not pop up so it shows 1 line.

**Comment by vasole** [comment]
You have to explicitly click on the reshape button.

![image](https://user-images.githubusercontent.com/5636251/93764104-d87e7b00-fc12-11ea-8938-00d6b0eb3cdc.png)

**Comment by vasole** [comment]
The following works as expected:

pymcapostbatch fluoXAS_0001.h5::/31.1/measurement/fx2_det0_NiKa
click on reshape and enter 300
load the whole measurement group (click on first icon on the left).

**Comment by vasole** [comment]
Selecting the whole measurement group at once from the command line does not work because the group contains items with different shapes. Once the proper size is known, the program only loads what is required.

**Comment by woutdenolf** [comment]
Ok I learned something new. So what is left to do maybe is:
1. allow the shape to be passed as a command line argument
2. allow the shape to be set before on image is loaded (in case started from the main GUI)
