### ISSUE TITLE
Transfer function of the optical element

### ISSUE THREAD

**Issue by ts8guest** [vasole/pymca#756]
Hello,

Our XRF setup is equipped with an optical element between the sample and the detector. We calculated the transfer function of the optical element and now we want to provide it for the analysis of spectra. In the file ClassMCATheory.py, we multiplied the rates (dict[ele][transition]['rate']) by the calculated function, but the analysis does not give correct elemental concentrations. How can we take into account the transmission function of the optical element?
Thanks in advance

**Comment by vasole** [comment]
Please, avoid using actual names and use things like @ts8guest GitHub users might want to remain anonymous.

Since the optical element will behave as an attenuator, my idea is to implement that functionality as a "user attenuator" consisting on a transmission table.

**Comment by vasole** [comment]
@ts8guest 

Current master adds support of user defined transmission tables. It requires fisx 1.2.0 (just released) to work.

In the ATTENUATORS tab of the fit configuration, you will see at the bottom a new tab named "User Attenuators". It will allow you to load a two column CSV file with the energies (in keV) and the transmission.

**Comment by ts8guest** [comment]
Thanks a lot.

**Comment by vasole** [comment]
You're welcome. Please note that this is included in the just released version 5.6.3
