### ISSUE TITLE
[PyMcaPostBatch] HDF5 dialog does not show anything

### ISSUE THREAD

**Issue by woutdenolf** [vasole/pymca#843]
```
pymcapostbatch /path/to/file.h5
```
![image](https://user-images.githubusercontent.com/7264703/160812970-bde4a4b4-2a7a-4247-b0e0-124ad314b85d.png)

Some quick debugging shows that `Hdf5SelectionDialog.exec_` is not called, neither by PyQt5 5.9.2 nore 5.15.6. The difference was that the 5.15.6 installation was done from source which has  commit https://github.com/vasole/pymca/commit/6da6ab52efe44e3eb3caa3efd4d42ff9b1a344e8

https://github.com/vasole/pymca/blob/871ff3cef08cf5d5fd0ba589be289c56eb3e0de3/PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py#L956-L963

So I guess it's fixed but we need to do the same for all our widget classes where we overwrite `exec_`.

**Comment by vasole** [comment]
Fortunately there are not too many. I take care.

![image](https://user-images.githubusercontent.com/5636251/160816304-ac08f52f-5786-4eea-b96e-148c718b28b0.png)

**Comment by vasole** [comment]
Do you want to test the pull request or I directly merge it?

**Comment by vasole** [comment]
Please wait! I have introduced a couple of bugs.

**Comment by vasole** [comment]
OK, bug corrected.
