### ISSUE TITLE
[HDF5] Change double-click behavior?

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#886]
To access `show info` via the context menu seems counter-intuitive.

To change the behavior would imply:

- Double-click as a short-cut to Show Information (equivalent to silx)
- Single-click to show the context menu
- Right-click unchanged (identical to context menu)

For datasets it seems fine, I am not so sure about groups.

**Comment by vasole** [comment]
Currently double-click on groups has an action on entry groups (apply last selection) and groups having the default attribute.

**Comment by vasole** [comment]
@woutdenolf 

Any comment on this issue? People do not know that the functionality of silx view is implemented in PyMca via right-click and show information.

**Comment by woutdenolf** [comment]
Can we preserve the plot update for double-clicking and entry with @default? So it does both.

**Comment by woutdenolf** [comment]
Hmmm not sure that makes sense. If we remove the current double-click behavior, is there another way you can apply the last selection?

**Comment by vasole** [comment]
I do not see other way. The question in that case is how many people are aware of (and use!) that functionality...

**Comment by vasole** [comment]
Probably I will have to end up adding some explicit configuration options for the user (default input filter, default action, traditional or silx behavior,...)

**Comment by vasole** [comment]
Let's keep the existing functionality.
