### ISSUE TITLE
HDF5Stack1D scanlist bug and no multi-hdf5-file support?

### ISSUE THREAD

**Issue by woutdenolf** [vasole/pymca#978]
Some test data:

```python
import logging
import h5py
import numpy
from PyMca5.PyMcaIO.HDF5Stack1D import HDF5Stack1D

logging.basicConfig(level=logging.DEBUG)

# 4 Bliss XRF scans in two files
counts = 100
with h5py.File("file1.h5", mode="w") as f:
    f.create_group("1.1")
    scan = f.create_group("2.1")
    measurement = scan.create_group("measurement")
    measurement["mca"] = numpy.full((3, 1024), counts, dtype=numpy.int32)
    counts += 1
    scan = f.create_group("3.1")
    measurement = scan.create_group("measurement")
    measurement["mca"] = numpy.full((3, 1024), counts, dtype=numpy.int32)
    counts += 1
with h5py.File("file2.h5", mode="w") as f:
    f.create_group("1.1")
    f.create_group("2.1")
    f.create_group("3.1")
    scan = f.create_group("4.1")
    measurement = scan.create_group("measurement")
    measurement["mca"] = numpy.full((3, 1024), counts, dtype=numpy.int32)
    counts += 1
    scan = f.create_group("5.1")
    measurement = scan.create_group("measurement")
    measurement["mca"] = numpy.full((3, 1024), counts, dtype=numpy.int32)
    counts += 1
```

## scanlist bug

To create a stack of two scans from one file:

```python
filelist = ["file1.h5"]
selection = {"y": "/measurement/mca"}
scanlist = ["2.1", "3.1"]
stack = HDF5Stack1D(filelist, selection, scanlist=scanlist)
assert stack.data.shape == (2, 3, 1024)
counts = 100
for values in stack.data:
    numpy.testing.assert_array_equal(values, counts)
    counts += 1
```

This fails with

```python
INFO:PyMca5.PyMcaIO.HDF5Stack1D:filelist = ['file1.h5']
INFO:PyMca5.PyMcaIO.HDF5Stack1D:selection = {'y': '/measurement/mca'}
INFO:PyMca5.PyMcaIO.HDF5Stack1D:scanlist = ['2.1', '3.1']
DEBUG:PyMca5.PyMcaIO.HDF5Stack1D:Retained number of files = 1
DEBUG:PyMca5.PyMcaIO.HDF5Stack1D:Retained number of scans = 2
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    stack = HDF5Stack1D(filelist, selection, scanlist=scanlist)
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/PyMca5/PyMcaIO/HDF5Stack1D.py", line 58, in __init__
    self.loadFileList(filelist, selection, scanlist)
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/PyMca5/PyMcaIO/HDF5Stack1D.py", line 260, in loadFileList
    yDataset = tmpHdf[path]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/h5py/_hl/group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)'
```

I see this several times:

https://github.com/vasole/pymca/blob/6e32d0b139d2e44aa2918a0b2490b04cf363222a/PyMca5/PyMcaIO/HDF5Stack1D.py#L479

I suspect this is wrong and should be `scan.split(".")[0]`? The first is the scan number, the second the subscan number.

I also don't understand `entryName = goodEntryNames[int(scan.split(".")[-1])-1]`. One missing scan number or non-good entry and this will fail. It will also fail when you have subscans, e.g. `scanlist = ["10.1", "10.2"]`.

## Multi-file support

Since `filelist` is a list I expected I would be able to do this

```python
filelist = ["file1.h5", "file2.h5"]
selection = {"y": "/measurement/mca"}
scanlist = ["2.1", "3.1", "4.1", "5.1"]
stack = HDF5Stack1D(filelist, selection, scanlist=scanlist)
assert stack.data.shape == (4, 3, 1024)
counts = 100
for values in stack.data:
    numpy.testing.assert_array_equal(values, counts)
    counts += 1
```

This fails with

```python
Traceback (most recent call last):
  File "test.py", line 51, in <module>
    stack = HDF5Stack1D(filelist, selection, scanlist=scanlist)
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/PyMca5/PyMcaIO/HDF5Stack1D.py", line 58, in __init__
    self.loadFileList(filelist, selection, scanlist)
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/PyMca5/PyMcaIO/HDF5Stack1D.py", line 508, in loadFileList
    yDataset = hdf[path]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/h5py/_hl/group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)'
```

I guess it cannot understand that `"2.1", "3.1"` belong to the first file and `"4.1", "5.1"` belong to the second file. Maybe we can support this by allowing `scanlist` to be a list of lists?

**Comment by vasole** [comment]
Your first case (two scans in single file) works for me (at least using the user interface).

**Comment by vasole** [comment]
OK. I got the root of the issue.

One could perform selections of scans based on the strings "1.1", "2.1" and so on `irrespective of the entry name`.

However, in the ESRF case, "1.1", "2.1" and so on are `actual entry names`. 

Forcing JUST_KEYS to False makes the things go through smoothly for the single file case.

**Comment by vasole** [comment]
The problem is the ambiguity. If the entry names would have any other name it would have worked.

#979 solves the single file case.

**Comment by vasole** [comment]
For instance, with #979 it will work on the single file as expected.

It will also work with two files containing 1.1 (empty), 2.1, 3.1 and 1.1, 4.1 and 5.1 providing as selection  2.0 and 3.0 you will get the selection you wanted: the second and the third scans of each file.

However, the returned shape is not what you would expect. The first dimension corresponds to the number of files and the second to the number of mca in each file. It was the convention used for EDF maps... So, instead of getting 4, 3, 1024 you will get 2, 6, 1024 back.

**Comment by woutdenolf** [comment]
> `(4, 3, 1024)` you will get `(2, 6, 1024)` back.

That's fine. But you cannot select any number of scans in any number of files right? If you have multiple files, you can only select scans based on their index in the list of entries (i.e. not based on their entry names) and the selected scans provides by the `scanlist` argument is applied to each file.

**Comment by vasole** [comment]
The idea of the API is that a stack spread among multiple files should have the same file structure on each of the files. If that is not the case, there is no simple and comfortable interface to offer to the user and it is more convenient to generate the equivalent as a single file with external links to all the scans of the files. In such case we go back to the selection of multiple scans on a single file that is properly working.

**Comment by vasole** [comment]
Can this be considered closed?
