### ISSUE TITLE
Sync Signal and Monitor index for 1D stacks

### ISSUE THREAD

**Issue by lrlunin** [vasole/pymca#994]
First of all, I would like to thank you all for such a beautiful which saved so much time for us. The last update with the support of 1D arrays in the scans was really amazing. We have not expected that such a feature will be in the program some day. But it's just perfect!

I would like to ask if it possible to sync a Monitor index with a Signal index for normalization.

We are currently have two 1D experimental channel with the intensity `I` over scattering vector `q` measuring over `delay`. One is `I(q)` a signal and other one is a reference for normalization `I_norm(q)`. The array `q` is not changing between measurements. Let's say we had a 3 `delay` measurement points.

Then we want to plot 3 lines:
1. X: `q, Index 1`, Signal: `I, Index 0`, Monitor `I_norm, Index 0`
2. X:  `q, Index 1`, Signal: `I, Index 1`, Monitor `I_norm, Index 1`
3. X:  `q, Index 1`, Signal: `I, Index 2`, Monitor `I_norm, Index 2`

![image](https://github.com/vasole/pymca/assets/1849145/61b683a0-7e79-4e59-9a98-8a3521a850fe)

If there is any opportunity to contribute to your software by adding this feature we would be happy to do it.

**Comment by vasole** [comment]
I see the problem of why synchronizing signal and monitor but not X axis...

One would expect to synchronize all of them.

**Comment by lrlunin** [comment]
> I see the problem of why synchronizing signal and monitor but not X axis...
> 
> One would expect to synchronize all of them.
Actually, that is what I have expected too. In the current version (5.8.1) I could only choose `Index: 1` for `X`. We have an array with scattering vector range in X and it can possibly be different for each acquisition. Sure, in the version with "full synchronization" it would be even better to sync all axis indexes.

**Comment by vasole** [comment]
> Actually, that is what I have expected too. In the current version (5.8.1) I could only choose `Index: 1` for `X`.

I have detected that while working on the synchronization issue.

It is solved by #995 

I am waiting for the CI to finish to merge it.

**Comment by vasole** [comment]
Please, give a try at  #996

**Comment by lrlunin** [comment]
> Please, give a try at #996

Just tested, works amazing as the rest of the program! Thank you very much.
